#!/usr/bin/env bash

echo 'xxh-plugin-prerun-docker: Details: https://docs.docker.com/engine/security/rootless/'
echo 'xxh-plugin-prerun-docker: Stop rootless docker'
killall rootlesskit
chmod -R 777 $XXH_DOCKER_RUNTIME
